### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by ngdangtu-vn** [the-moebius/grammy-fluent#4]
For now, do we have any option that allow me to use Deno with languages support or at least let me leave placeholder for future update?

**Comment by slavafomin** [comment]
Hey! There is no love for Deno here. Please try one of the forks.

**Comment by ngdangtu-vn** [comment]
Actually I've done manual converting this plugin to deno version with a port of @moebius/fluent which is `better_fluent`. Can I submit my version?

**Comment by KnorpelSenf** [comment]
@ngdangtu-vn please see #3. This project will forever be limited to Node.js. We want to create a different project in the future to bring i18n support to Deno for grammY.
